# Task to Install Third Party pip Packages
#
# Inputs:
#   * app-git: GitHub repo with an Application Source
#   * OW_APP_PYTHON_VERSION: any specific Python Version you want to pull, default is "python"
#   * OW_APP_PATH: path to application directory within the GitHub repo, default is ""
#
# OutPuts:
#   * app-git: GitHub repo with an Application Source along with all the dependencies installed
#
# Application source is cloned under /workspace/<resource-name> by default if targetPath is not specified.
#
# This task installs third party packages under /workspace/<resource-name>/<app_path>/
#
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-install-pip-packages
spec:
  inputs:
    resources:
      - name: app-git
        type: git
    params:
      - name: OW_APP_PYTHON_VERSION
        default: "python"
        description: "Any specific Python version needed to compile/run application source on"
      - name: OW_APP_PATH
        default: ""
        description: "Relative or Absolute path to the application source"
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: install-python-packages
      image: $(inputs.params.OW_APP_PYTHON_VERSION)
      script: |
        #!/usr/bin/env bash
        set -xe
        echo $(inputs.params.OW_APP_PATH)
        if [ -z "$(inputs.params.OW_APP_PATH)" ]; then
          OW_APP_PATH=$(inputs.resources.app-git.path)
        else
          OW_APP_PATH=$(inputs.params.OW_APP_PATH)
        fi
        echo $OW_APP_PATH
        cd $OW_APP_PATH
        echo "Starting to install Python Packages under $OW_APP_PATH"
        pip install virtualenv
        virtualenv virtualenv
        source virtualenv/bin/activate
        pip install -r requirements.txt
        if [ $? = 0 ]; then
          echo "Successfully finished installing Python Packages under $OW_APP_PATH"
        else
          echo "Failed to install Python Packages under $OW_APP_PATH"
        fi
    - name: copy-app-git-to-output-workspace
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -xe
        cp -r $(inputs.resources.app-git.path)/* $(outputs.resources.app-git.path)
        ls -R $(outputs.resources.app-git.path)
